services:
  statistic_db:
    image: postgres:15
    container_name: statistic_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - statistic_postgres_data:/var/lib/postgresql/data
    networks:
      - statistic_network

  metabase:
    image: metabase/metabase:latest
    container_name: statistic_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2  # O Metabase usa um banco interno leve para guardar seus gráficos salvos
    restart: always
    networks:
      - statistic_network

networks:
  statistic_network:
    driver: bridge

volumes:
  statistic_postgres_data: